### ISSUE TITLE
When nickname is identical to first name, updates to first name should affect nickname too

### ISSUE THREAD

**Issue by seancolsen** [ginkgostreet/com.ginkgostreet.nickfix#2]
Steps to reproduce: 

1. Establish a contact where `first_name` is *Foobar* and `nick_name` is *Foobar*
1. Change `first_name` to *Bazbat*
1. Expect `nick_name` to also become *Bazbat*
1. Observe that `nick_name` remains *Foobar*

**Comment by universalhandle** [comment]
I'm not sure I agree this change should be made, but I'm open to debating it. The extension's scope seeks to be narrow:

> This extension will keep the nickname field populated at all times. The nickname will default
to the first name, unless another value is supplied by the user. If an existing value for
the nickname is removed, the nickname will be reset to the first name.

Here's a scenario in which I wouldn't want the requested behavior to occur. When I introduced myself to you, I did so as "Frank J. Gómez." That's what went into your database. If you had nickfix installed, it set my nickname to "Frank." Later (right now, actually!), you learned my name is actually "Francisco." Obsessive data hygienist that you are, you immediately pull up your CRM and update my first name. We'd want my nickname to remain "Frank," since that is how everyone knows me.

Have two cents to offer, @axon-obriend?

**Comment by seancolsen** [comment]
mmm, good point @GinkgoFJG 

I was thinking about this case: You signed up for an event with the first name "Frnk". Later I learn your name is actually "Frank" and go change "Frnk" to "Frank". 

In thinking about this more, I don't think it would be possible for the extension to deal with both-use cases perfectly. And with your use-case being much more common than mine, I now agree that the extension should continue to function as-is in order to accommodate your use case. 

I think we can close this issue now.
